
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:228 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The target system is: Android - 1 - aarch64
      The host system is: Linux - 5.15.119-android13-8-gdae8b7f03305-ab1764128685 - aarch64
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang 
      Build flags: -g;-DANDROID;-fdata-sections;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-D_FORTIFY_SOURCE=2;-Wformat;-Werror=format-security
      Id flags: -c;--target=aarch64-none-linux-android21 
      
      The output was:
      0
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"
      
      The C compiler identification is Clang, found in:
        /sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/3.28.3/CompilerIdC/CMakeCCompilerId.o
      
  -
    kind: "message-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:3 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ 
      Build flags: -g;-DANDROID;-fdata-sections;-ffunction-sections;-funwind-tables;-fstack-protector-strong;-no-canonical-prefixes;-D_FORTIFY_SOURCE=2;-Wformat;-Werror=format-security
      Id flags: -c;--target=aarch64-none-linux-android21 
      
      The output was:
      0
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"
      
      The CXX compiler identification is Clang, found in:
        /sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/3.28.3/CompilerIdCXX/CMakeCXXCompilerId.o
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-mNEuY0"
      binary: "/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-mNEuY0"
    cmakeVariables:
      ANDROID_ABI: "arm64-v8a"
      ANDROID_ARM_MODE: "thumb"
      ANDROID_PIE: "TRUE"
      ANDROID_PLATFORM: "android-21"
      ANDROID_STL: "c++_static"
      ANDROID_TOOLCHAIN: "clang"
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-scan-deps"
      CMAKE_CXX_COMPILER_TARGET: "aarch64-none-linux-android21"
      CMAKE_C_COMPILER_TARGET: "aarch64-none-linux-android21"
      CMAKE_C_FLAGS: "-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat "
      CMAKE_C_FLAGS_DEBUG: "-fno-limit-debug-info "
      CMAKE_EXE_LINKER_FLAGS: "-static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  "
      CMAKE_POSITION_INDEPENDENT_CODE: "TRUE"
      CMAKE_SYSROOT: "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: '/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-mNEuY0'
        
        Run Build Command(s): /root/Android/cmake/3.22.1/bin/ninja -v cmTC_ff1a5
        [1/2] /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat   -fPIE   -v -MD -MT CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -MF CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o.d -o CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        Ubuntu clang version 18.1.3 (1ubuntu1)
        Target: aarch64-none-linux-android21
        Thread model: posix
        InstalledDir: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin
         (in-process)
         "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang" -cc1 -triple aarch64-none-linux-android21 -emit-obj -mrelax-all -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name CMakeCCompilerABI.c -mrelocation-model pic -pic-level 2 -pic-is-pie -mframe-pointer=non-leaf -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu generic -target-feature +v8a -target-feature +fp-armv8 -target-feature +neon -target-feature +fix-cortex-a53-835769 -target-abi aapcs -debug-info-kind=constructor -dwarf-version=4 -debugger-tuning=gdb -fdebug-compilation-dir=/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-mNEuY0 -v -ffunction-sections -fdata-sections -fcoverage-compilation-dir=/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-mNEuY0 -resource-dir /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18 -dependency-file CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o.d -MT CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -sys-header-deps -D ANDROID -D _FORTIFY_SOURCE=2 -isysroot /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -internal-isystem /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/include -internal-isystem /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include -internal-externc-isystem /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android -internal-externc-isystem /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/include -internal-externc-isystem /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include -Wformat -ferror-limit 19 -femulated-tls -stack-protector 2 -fno-signed-char -fgnuc-version=4.2.1 -fskip-odr-check-in-gmf -target-feature -fmv -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -x c /usr/share/cmake-3.28/Modules/CMakeCCompilerABI.c
        clang -cc1 version 18.1.3 based upon LLVM 18.1.3 default target aarch64-unknown-linux-gnu
        ignoring nonexistent directory "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/local/include"
        ignoring nonexistent directory "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/include"
        #include "..." search starts here:
        #include <...> search starts here:
         /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/include
         /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/aarch64-linux-android
         /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
        End of search list.
        [2/2] : && /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments   -v CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -o cmTC_ff1a5   && :
        FAILED: cmTC_ff1a5 
        : && /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments   -v CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -o cmTC_ff1a5   && :
        Ubuntu clang version 18.1.3 (1ubuntu1)
        Target: aarch64-none-linux-android21
        Thread model: posix
        InstalledDir: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin
         "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/ld.lld" --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -EL --fix-cortex-a53-843419 -z now -z relro -z max-page-size=4096 --hash-style=both --build-id --eh-frame-hdr -m aarch64linux -pie -dynamic-linker /system/bin/linker64 -o cmTC_ff1a5 /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/crtbegin_dynamic.o -L/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/lib/clang/18/lib/linux/aarch64 -L/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21 -L/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android -L/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib --build-id=sha1 --no-rosegment --no-undefined-version --fatal-warnings --no-undefined CMakeFiles/cmTC_ff1a5.dir/CMakeCCompilerABI.c.o -lgcc -ldl -lc -lgcc -ldl /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/crtend_android.o
        ld.lld: error: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/libgcc.a: archive member 'empty_obj' is neither ET_REL nor LLVM bitcode
        ld.lld: error: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/libgcc.a: archive member 'empty_obj' is neither ET_REL nor LLVM bitcode
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
  -
    kind: "try_compile-v1"
    backtrace:
      - "/usr/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:56 (try_compile)"
      - "CMakeLists.txt:3 (project)"
    checks:
      - "Check for working C compiler: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang"
    directories:
      source: "/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-jy6Rbl"
      binary: "/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-jy6Rbl"
    cmakeVariables:
      ANDROID_ABI: "arm64-v8a"
      ANDROID_ARM_MODE: "thumb"
      ANDROID_PIE: "TRUE"
      ANDROID_PLATFORM: "android-21"
      ANDROID_STL: "c++_static"
      ANDROID_TOOLCHAIN: "clang"
      CMAKE_CXX_COMPILER_CLANG_SCAN_DEPS: "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang-scan-deps"
      CMAKE_CXX_COMPILER_TARGET: "aarch64-none-linux-android21"
      CMAKE_C_COMPILER_TARGET: "aarch64-none-linux-android21"
      CMAKE_C_FLAGS: "-g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security "
      CMAKE_C_FLAGS_DEBUG: "-fno-limit-debug-info "
      CMAKE_EXE_LINKER_FLAGS: "-static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments  "
      CMAKE_POSITION_INDEPENDENT_CODE: "TRUE"
      CMAKE_SYSROOT: "/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot"
    buildResult:
      variable: "CMAKE_C_COMPILER_WORKS"
      cached: true
      stdout: |
        Change Dir: '/sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-jy6Rbl'
        
        Run Build Command(s): /root/Android/cmake/3.22.1/bin/ninja -v cmTC_0378f
        [1/2] /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot   -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security   -fPIE -MD -MT CMakeFiles/cmTC_0378f.dir/testCCompiler.c.o -MF CMakeFiles/cmTC_0378f.dir/testCCompiler.c.o.d -o CMakeFiles/cmTC_0378f.dir/testCCompiler.c.o -c /sdcard/TaiziHermes/fbx/.bcxx_test/CMakeFiles/CMakeScratch/TryCompile-jy6Rbl/testCCompiler.c
        [2/2] : && /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments CMakeFiles/cmTC_0378f.dir/testCCompiler.c.o -o cmTC_0378f  -latomic -lm && :
        FAILED: cmTC_0378f 
        : && /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=aarch64-none-linux-android21 --sysroot=/root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments CMakeFiles/cmTC_0378f.dir/testCCompiler.c.o -o cmTC_0378f  -latomic -lm && :
        ld.lld: error: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/libgcc.a: archive member 'empty_obj' is neither ET_REL nor LLVM bitcode
        ld.lld: error: /root/Android/ndk/27.0.12077973/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/21/libgcc.a: archive member 'empty_obj' is neither ET_REL nor LLVM bitcode
        clang: error: linker command failed with exit code 1 (use -v to see invocation)
        ninja: build stopped: subcommand failed.
        
      exitCode: 1
...
